/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package sda.ghidra.function;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-05-21")
public class SFunctionRange implements org.apache.thrift.TBase<SFunctionRange, SFunctionRange._Fields>, java.io.Serializable, Cloneable, Comparable<SFunctionRange> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SFunctionRange");

  private static final org.apache.thrift.protocol.TField MIN_OFFSET_FIELD_DESC = new org.apache.thrift.protocol.TField("minOffset", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField MAX_OFFSET_FIELD_DESC = new org.apache.thrift.protocol.TField("maxOffset", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SFunctionRangeStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SFunctionRangeTupleSchemeFactory();

  public int minOffset; // required
  public int maxOffset; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MIN_OFFSET((short)1, "minOffset"),
    MAX_OFFSET((short)2, "maxOffset");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MIN_OFFSET
          return MIN_OFFSET;
        case 2: // MAX_OFFSET
          return MAX_OFFSET;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MINOFFSET_ISSET_ID = 0;
  private static final int __MAXOFFSET_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MIN_OFFSET, new org.apache.thrift.meta_data.FieldMetaData("minOffset", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MAX_OFFSET, new org.apache.thrift.meta_data.FieldMetaData("maxOffset", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SFunctionRange.class, metaDataMap);
  }

  public SFunctionRange() {
  }

  public SFunctionRange(
    int minOffset,
    int maxOffset)
  {
    this();
    this.minOffset = minOffset;
    setMinOffsetIsSet(true);
    this.maxOffset = maxOffset;
    setMaxOffsetIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SFunctionRange(SFunctionRange other) {
    __isset_bitfield = other.__isset_bitfield;
    this.minOffset = other.minOffset;
    this.maxOffset = other.maxOffset;
  }

  public SFunctionRange deepCopy() {
    return new SFunctionRange(this);
  }

  @Override
  public void clear() {
    setMinOffsetIsSet(false);
    this.minOffset = 0;
    setMaxOffsetIsSet(false);
    this.maxOffset = 0;
  }

  public int getMinOffset() {
    return this.minOffset;
  }

  public SFunctionRange setMinOffset(int minOffset) {
    this.minOffset = minOffset;
    setMinOffsetIsSet(true);
    return this;
  }

  public void unsetMinOffset() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MINOFFSET_ISSET_ID);
  }

  /** Returns true if field minOffset is set (has been assigned a value) and false otherwise */
  public boolean isSetMinOffset() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MINOFFSET_ISSET_ID);
  }

  public void setMinOffsetIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MINOFFSET_ISSET_ID, value);
  }

  public int getMaxOffset() {
    return this.maxOffset;
  }

  public SFunctionRange setMaxOffset(int maxOffset) {
    this.maxOffset = maxOffset;
    setMaxOffsetIsSet(true);
    return this;
  }

  public void unsetMaxOffset() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MAXOFFSET_ISSET_ID);
  }

  /** Returns true if field maxOffset is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxOffset() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MAXOFFSET_ISSET_ID);
  }

  public void setMaxOffsetIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MAXOFFSET_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case MIN_OFFSET:
      if (value == null) {
        unsetMinOffset();
      } else {
        setMinOffset((java.lang.Integer)value);
      }
      break;

    case MAX_OFFSET:
      if (value == null) {
        unsetMaxOffset();
      } else {
        setMaxOffset((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MIN_OFFSET:
      return getMinOffset();

    case MAX_OFFSET:
      return getMaxOffset();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MIN_OFFSET:
      return isSetMinOffset();
    case MAX_OFFSET:
      return isSetMaxOffset();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SFunctionRange)
      return this.equals((SFunctionRange)that);
    return false;
  }

  public boolean equals(SFunctionRange that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_minOffset = true;
    boolean that_present_minOffset = true;
    if (this_present_minOffset || that_present_minOffset) {
      if (!(this_present_minOffset && that_present_minOffset))
        return false;
      if (this.minOffset != that.minOffset)
        return false;
    }

    boolean this_present_maxOffset = true;
    boolean that_present_maxOffset = true;
    if (this_present_maxOffset || that_present_maxOffset) {
      if (!(this_present_maxOffset && that_present_maxOffset))
        return false;
      if (this.maxOffset != that.maxOffset)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + minOffset;

    hashCode = hashCode * 8191 + maxOffset;

    return hashCode;
  }

  @Override
  public int compareTo(SFunctionRange other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetMinOffset()).compareTo(other.isSetMinOffset());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinOffset()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.minOffset, other.minOffset);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMaxOffset()).compareTo(other.isSetMaxOffset());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxOffset()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxOffset, other.maxOffset);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SFunctionRange(");
    boolean first = true;

    sb.append("minOffset:");
    sb.append(this.minOffset);
    first = false;
    if (!first) sb.append(", ");
    sb.append("maxOffset:");
    sb.append(this.maxOffset);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SFunctionRangeStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SFunctionRangeStandardScheme getScheme() {
      return new SFunctionRangeStandardScheme();
    }
  }

  private static class SFunctionRangeStandardScheme extends org.apache.thrift.scheme.StandardScheme<SFunctionRange> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SFunctionRange struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MIN_OFFSET
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.minOffset = iprot.readI32();
              struct.setMinOffsetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MAX_OFFSET
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.maxOffset = iprot.readI32();
              struct.setMaxOffsetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SFunctionRange struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MIN_OFFSET_FIELD_DESC);
      oprot.writeI32(struct.minOffset);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MAX_OFFSET_FIELD_DESC);
      oprot.writeI32(struct.maxOffset);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SFunctionRangeTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SFunctionRangeTupleScheme getScheme() {
      return new SFunctionRangeTupleScheme();
    }
  }

  private static class SFunctionRangeTupleScheme extends org.apache.thrift.scheme.TupleScheme<SFunctionRange> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SFunctionRange struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMinOffset()) {
        optionals.set(0);
      }
      if (struct.isSetMaxOffset()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMinOffset()) {
        oprot.writeI32(struct.minOffset);
      }
      if (struct.isSetMaxOffset()) {
        oprot.writeI32(struct.maxOffset);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SFunctionRange struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.minOffset = iprot.readI32();
        struct.setMinOffsetIsSet(true);
      }
      if (incoming.get(1)) {
        struct.maxOffset = iprot.readI32();
        struct.setMaxOffsetIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

