/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package sda.ghidra.datatype;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-05-21")
public class SDataTypeClass implements org.apache.thrift.TBase<SDataTypeClass, SDataTypeClass._Fields>, java.io.Serializable, Cloneable, Comparable<SDataTypeClass> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SDataTypeClass");

  private static final org.apache.thrift.protocol.TField STRUCT_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("structType", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SDataTypeClassStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SDataTypeClassTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable SDataTypeStructure structType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STRUCT_TYPE((short)1, "structType");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STRUCT_TYPE
          return STRUCT_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STRUCT_TYPE, new org.apache.thrift.meta_data.FieldMetaData("structType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SDataTypeStructure.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SDataTypeClass.class, metaDataMap);
  }

  public SDataTypeClass() {
  }

  public SDataTypeClass(
    SDataTypeStructure structType)
  {
    this();
    this.structType = structType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SDataTypeClass(SDataTypeClass other) {
    if (other.isSetStructType()) {
      this.structType = new SDataTypeStructure(other.structType);
    }
  }

  public SDataTypeClass deepCopy() {
    return new SDataTypeClass(this);
  }

  @Override
  public void clear() {
    this.structType = null;
  }

  @org.apache.thrift.annotation.Nullable
  public SDataTypeStructure getStructType() {
    return this.structType;
  }

  public SDataTypeClass setStructType(@org.apache.thrift.annotation.Nullable SDataTypeStructure structType) {
    this.structType = structType;
    return this;
  }

  public void unsetStructType() {
    this.structType = null;
  }

  /** Returns true if field structType is set (has been assigned a value) and false otherwise */
  public boolean isSetStructType() {
    return this.structType != null;
  }

  public void setStructTypeIsSet(boolean value) {
    if (!value) {
      this.structType = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case STRUCT_TYPE:
      if (value == null) {
        unsetStructType();
      } else {
        setStructType((SDataTypeStructure)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case STRUCT_TYPE:
      return getStructType();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case STRUCT_TYPE:
      return isSetStructType();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SDataTypeClass)
      return this.equals((SDataTypeClass)that);
    return false;
  }

  public boolean equals(SDataTypeClass that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_structType = true && this.isSetStructType();
    boolean that_present_structType = true && that.isSetStructType();
    if (this_present_structType || that_present_structType) {
      if (!(this_present_structType && that_present_structType))
        return false;
      if (!this.structType.equals(that.structType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetStructType()) ? 131071 : 524287);
    if (isSetStructType())
      hashCode = hashCode * 8191 + structType.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SDataTypeClass other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetStructType()).compareTo(other.isSetStructType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStructType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.structType, other.structType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SDataTypeClass(");
    boolean first = true;

    sb.append("structType:");
    if (this.structType == null) {
      sb.append("null");
    } else {
      sb.append(this.structType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (structType != null) {
      structType.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SDataTypeClassStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SDataTypeClassStandardScheme getScheme() {
      return new SDataTypeClassStandardScheme();
    }
  }

  private static class SDataTypeClassStandardScheme extends org.apache.thrift.scheme.StandardScheme<SDataTypeClass> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SDataTypeClass struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STRUCT_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.structType = new SDataTypeStructure();
              struct.structType.read(iprot);
              struct.setStructTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SDataTypeClass struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.structType != null) {
        oprot.writeFieldBegin(STRUCT_TYPE_FIELD_DESC);
        struct.structType.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SDataTypeClassTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SDataTypeClassTupleScheme getScheme() {
      return new SDataTypeClassTupleScheme();
    }
  }

  private static class SDataTypeClassTupleScheme extends org.apache.thrift.scheme.TupleScheme<SDataTypeClass> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SDataTypeClass struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetStructType()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetStructType()) {
        struct.structType.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SDataTypeClass struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.structType = new SDataTypeStructure();
        struct.structType.read(iprot);
        struct.setStructTypeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

